name: chat-with-files

services:
  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  embedder:
    build: ./embed-server
    ports:
      - "8001:8000"     # container:8000 -> host:8001
    env_file:
      - .env

  worker:
    build: ./server
    command: ["node", "worker.js"]
    restart: unless-stopped
    depends_on: [valkey, mongo, qdrant, embedder]
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB: docchat
      REDIS_HOST: valkey
      REDIS_PORT: "6379"
      QDRANT_URL: http://qdrant:6333
      EMBEDDINGS_URL: http://embedder:8000/embeddings
      TESSDATA_PREFIX: /usr/share/tesseract-ocr/4.00/tessdata

volumes:
  mongo_data:
  qdrant_data:
