name: Build & Push Docker Images

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}       # allow manual runs

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: docker.io
  IMAGE_NAMESPACE: ${{ secrets.DOCKERHUB_USERNAME }}
  PLATFORMS: linux/amd64,linux/arm64
  SHORT_SHA: ${{ github.sha.substr(0,7) }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------- SERVER ----------
      - name: Build & Push server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/docchat-server:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/docchat-server:${{ env.SHORT_SHA }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha,scope=server
          cache-to: type=gha,mode=max,scope=server
          provenance: false
          sbom: false

      # ---------- CLIENT ----------
      - name: Build & Push client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/docchat-client:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/docchat-client:${{ env.SHORT_SHA }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha,scope=client
          cache-to: type=gha,mode=max,scope=client
          provenance: false
          sbom: false

      # ---------- EMBEDDER ----------
      - name: Build & Push embedder
        uses: docker/build-push-action@v6
        with:
          context: ./embed-server
          file: ./embed-server/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/docchat-embedder:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/docchat-embedder:${{ env.SHORT_SHA }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha,scope=embedder
          cache-to: type=gha,mode=max,scope=embedder
          provenance: false
          sbom: false
